name: Rcc
on:
    workflow_dispatch:
        # enables manual triggering
    push:
        branches:
            - bluecopa_build

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v3
              with:
                  go-version: '1.20.x'
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'
            - uses: actions/checkout@v1
            - name: What
              run: rake what
            - name: Building
              run: |
                rake clean build
                cp certificate/codesign.pfx build/.
            - name: Publish Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: build-artifact
                path: build
    macos:
        name: MacOs Code Signing
        runs-on: macos-latest
        needs:
          - build
        steps:
          - name: Download Shared Directory
            uses: actions/download-artifact@v2
            with:
              name: build-artifact
          - name: Setup Keychain and Import Certificate
            run: |
              pwd
              ls -ltr
              security create-keychain -p "" build.keychain
              security import codesign.pfx -k build.keychain -P asdf -T /usr/bin/codesign
              security list-keychains -s build.keychain
              security unlock-keychain -p "" build.keychain
              security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
            shell: /bin/bash -e {0}

          - name: Sign Executable
            run: |
              ls -ltr
              security find-certificate -a -e "support@bluecopa.com" build.keychain
              ls -ltr
              security find-certificate -c "Bluecopa" -p /Users/runner/Library/Keychains/build.keychain-db | openssl x509 -inform pem -noout -subject
              ls -ltr
              codesign -s "Bluecopa" -o runtime --timestamp macos64/rcc
              ls -ltr

          - name: Archive Artifacts
            uses: actions/upload-artifact@v2
            with:
              name: signed-executable
              path: build-artifact

