name: Rcc
on:
    workflow_dispatch:
        # enables manual triggering
    push:
        branches:
            - bluecopa_build

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v3
              with:
                  go-version: '1.20.x'
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'
            - uses: actions/checkout@v1
            - name: What
              run: rake what
            - name: Building
              run: |
                rake clean build
                cp self_signed.p12 build/.
            - name: Publish Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: build-artifact
                path: build
    macos:
        name: MacOs Code Signing
        runs-on: macos-latest
        needs:
          - build
        steps:
          - name: Download Shared Directory
            uses: actions/download-artifact@v2
            with:
              name: build-artifact
          - name: Decode Certificate
            run: cat certificate/codesign.txt | base64 --decode > codesign.pfx

          - name: Install Certificate
            run: |
              security create-keychain -p "" build.keychain
              security import codesign.pfx -k build.keychain -P asdf -T /usr/bin/codesign
              security list-keychains -s build.keychain
              security unlock-keychain -p "" build.keychain
              security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          - name: Sign Executable
            run: |
              codesign --sign "Bluecopa" --keychain build.keychain --timestamp --options runtime 

          - name: Archive Artifacts
            uses: actions/upload-artifact@v2
            with:
              name: signed-executable
              path: build-artifact

