name: Rcc
on:
    workflow_dispatch:
        # enables manual triggering
    push:
        branches:
            - bluecopa_build

jobs:
    macos:
        name: MacOs
        runs-on: macos-11.0
        steps:
            - uses: actions/setup-go@v3
              with:
                  go-version: '1.20.x'
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'
            - uses: actions/checkout@v1
            - name: What
              run: rake what
            - name: Building
              run: rake clean build
