name: Rcc
on:
    workflow_dispatch:
        # enables manual triggering
    push:
        branches:
            - bluecopa_build

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v3
              with:
                  go-version: '1.20.x'
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'
            - uses: actions/checkout@v1
            - name: What
              run: rake what
            - name: Building
              run: rake clean build
            - name: Publish Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: build-artifact
                path: build
    macos:
        name: MacOs
        runs-on: macos-11.0
        needs:
          - build
        steps:
          - name: Download Shared Directory
            uses: actions/download-artifact@v2
            with:
              name: build-artifact
          - name: Codesign executable
            env:
              MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
              MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
            run: |
              ls -ltr
